# Generated by Django 2.0.2 on 2018-03-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20180324_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='who_get_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_marks', to='schoolclasses.Pupil'),
        ),
    ]
